# Generated by Django 4.2.2 on 2023-10-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_book_user_tag_user_simpleuser_userprofile_simpleuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='simpleuser',
        ),
        migrations.DeleteModel(
            name='SimpleUser',
        ),
    ]
