# Generated by Django 4.2.2 on 2023-10-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bookshelf_book_bookshelf_tag_bookshelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrow_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
